apiVersion: promoter.argoproj.io/v1alpha1
kind: ArgoCDCommitStatus
metadata:
  name: sample-service-argocd-health
  namespace: promoter-system
spec:
  promotionStrategyRef:
    name: sample-service
  applicationSelector:
    matchLabels:
      app.kubernetes.io/name: sample-service
